### ISSUE TITLE
Spamování API

### ISSUE THREAD

**Issue by JustScreaMy** [BufWare/bufware-web#2]
https://github.com/BufWare/bufware-web/blob/713ae41c3441c0e23a99b9af918685b0292e7dfb/src/views/CustomerOrderCheckout.js#L11-L17

Toto je blbé protože se komponenta vytvoří dvakrát a proto to bude házet 429

**Comment by Th0be** [comment]
Opraveno přesunutím useEffectu do nadřazené komponenty.
